### ISSUE TITLE
Not Working on Unity 4.7.1 

### ISSUE THREAD

**Issue by lijuicsoft** [playgameservices/play-games-plugin-for-unity#1231]
1.Imported GooglePlayGamesPlugin-0.9.10
2.Imported sample projects 

showing following errors
1. *error CS0234: The type or namespace name `SavedGame' does not exist in the namespace `GooglePlayGames.BasicApi'. Are you missing an assembly reference?*
