### ISSUE TITLE
does not implement interface member

### ISSUE THREAD

**Issue by mushdevstudio** [playgameservices/play-games-plugin-for-unity#2777]
I am currently using Unity 2019.
Since updating play-games-plugin-for-unity to 10.0.5 I get these 4 errors:

Assets/GooglePlayGames/Platforms/Native/NativeClient.cs(37,33): error CS0535: 'NativeClient' does not implement interface member 'IPlayGamesClient.GetAnotherServerAuthCode(bool, Action<string>)'

Assets/GooglePlayGames/Platforms/Native/NativeSavedGameClient.cs(102,48): error CS0535: 'NativeSavedGameClient.NativeConflictResolver' does not implement interface member 'IConflictResolver.ResolveConflict(ISavedGameMetadata, SavedGameMetadataUpdate, byte[])'

Assets/GooglePlayGames/Platforms/Native/NativeTurnBasedMultiplayerClient.cs(29,53): error CS0535: 'NativeTurnBasedMultiplayerClient' does not implement interface member 'ITurnBasedMultiplayerClient.GetMatch(string, Action<bool, TurnBasedMatch>)'

Assets/GooglePlayGames/Platforms/Native/NativeTurnBasedMultiplayerClient.cs(29,53): error CS0535: 'NativeTurnBasedMultiplayerClient' does not implement interface member 'ITurnBasedMultiplayerClient.Dismiss(TurnBasedMatch)'

**Comment by olehkuznetsov** [comment]
Just remove the plugin folder from assets and reimport it again, please. It seems you still have files from a previous plugin version.

**Comment by mushdevstudio** [comment]
> Just remove the plugin folder from assets and reimport it again, please. It seems you still have files from a previous plugin version.

Thanks - that worked perfectly
