### ISSUE TITLE
GetAccessToken Failing - Non-success returned from fetch: 8

### ISSUE THREAD

**Issue by tfendt** [playgameservices/play-games-plugin-for-unity#1339]
There seems to be in issue with getting an AccessToken. I can successfully get the users email but when I try to get the access token I am getting:
!!! [Play Games Plugin DLL] 08/23/16 15:27:46 -05:00 WARNING: Non-success returned from fetch: 8

It looks like there is a missing file in the unity package.

```
Unity   :  [Play Games Plugin DLL] 08/23/16 15:27:46 -05:00 DEBUG: Invoking user callback on game thread
Unity   :  
Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
Unity   : 
TokenFragment: Fragment exists.. and not selecting calling processRequests
TokenFragment: Calling doGetToken for e: false a:true i:false
TokenFragment: Done with processRequests!
08-23 15:27:46.311 18348 24486 D TokenFragment: getting accessToken for test.user@gmail.com
08-23 15:27:46.311 18348 24486 E TokenFragment: Exception getting access token
08-23 15:27:46.311 18348 24486 E TokenFragment: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/GoogleAuthUtil;
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:226)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.lang.Thread.run(Thread.java:818)
08-23 15:27:46.311 18348 24486 E TokenFragment: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.GoogleAuthUtil" on path: DexPathList[[zip file "/mnt/asec/com.tntgames.game-2/base.apk"],nativeLibraryDirectories=[/mnt/asec/com.tntgames.game-2/lib/arm, /mnt/asec/com.tntgames.game-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
08-23 15:27:46.311 18348 24486 E TokenFragment: 	... 8 more
08-23 15:27:46.311 18348 24486 E TokenFragment: 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.auth.GoogleAuthUtil
08-23 15:27:46.311 18348 24486 E TokenFragment: 		at java.lang.Class.classForName(Native Method)
08-23 15:27:46.311 18348 24486 E TokenFragment: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
08-23 15:27:46.311 18348 24486 E TokenFragment: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
08-23 15:27:46.311 18348 24486 E TokenFragment: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
08-23 15:27:46.311 18348 24486 E TokenFragment: 		... 9 more
08-23 15:27:46.311 18348 24486 E TokenFragment: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
08-23 15:27:46.311 18348 24486 D TokenFragment: Done with tokenRequest status: 8
08-23 15:27:46.311 18348 18348 D TokenFragment: onPostExecute for the token fetch
08-23 15:27:46.311 18348 18361 I Unity   : ---- [0] -- 1048605
08-23 15:27:46.311 18348 18361 I Unity   :  
08-23 15:27:46.311 18348 18361 I Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
08-23 15:27:46.311 18348 18361 I Unity   : 
08-23 15:27:46.321 18348 18361 W Unity   : !!! [Play Games Plugin DLL] 08/23/16 15:27:46 -05:00 WARNING: Non-success returned from fetch: 8
08-23 15:27:46.321 18348 18361 W Unity   :  
08-23 15:27:46.321 18348 18361 W Unity   : (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
```

How do I add the class it is looking for? I have the following SDKs installed:
https://puu.sh/qLSEZ/675a693d6a.png

**Comment by tfendt** [comment]
Here are the client libs in the plugin folder:
https://puu.sh/qMezd/e6dfd09e8b.png

Forgot to mention, I am using the latest plugin 0.9.34 and unity version 5.3.5 f1

**Comment by felipesticksports** [comment]
I do have the same error and pretty much the same configuration and the weird thing is that I had this working fine until a week ago or so, when it stopped working and I got the same message as you:

WARNING: Non-success returned from fetch: 8

As far as I remember the only thing that we did here is that we updated whatever Android SDK Manager suggested, so I'm thinking of trying to revert to a couple of older versions and see how it goes.

**Comment by felipesticksports** [comment]
So yeah now it's fixed again here. For that I had to force this plugin to use play services version 9.0.2 instead of the 9.4.0 which it was using before.

The change I did was in PluginVersion.cs, line 41, from:

public const string PlayServicesVersionConstraint = "9+";

to:

public const string PlayServicesVersionConstraint = "9.0.2";

If that doesn't work for you, open the file GoogleDependencyGooglePlayGames.xml on the folder ProjectSettings from your project and change the version there as well.

After that all you need is right click on unity, then Google Play Services -> Resolve Client Jars.

I hope that solves the issue for you as well and I also hope to find out soon why it's not working with the 9.4.0 version in the first place.

**Comment by tfendt** [comment]
Think I found the issue. In May google moved the GoogleAuthUtil. https://developers.google.com/android/guides/releases#may_2016_-_v90

> GoogleAuthUtil has moved to the -auth API split in the Google Play services SDK. If your app uses GoogleAuthUtil.getToken() you may see an error similar to the following:

> Error:(xx, xx) error: package com.google.android.gms.auth does not exist

> Error:(xx, xx) error: cannot find symbol variable GoogleAuthUtil

> If you need to access the REST API on Android, include the -auth split in your build.gradle file:

> compile 'com.google.android.gms:play-services-auth:9.0.1'

> Otherwise, we recommend migrating your app to the Google Sign-In API to incorporate the latest improvements in security and user experience into your app. To learn more, see our guide to Google Sign In best practices.

**Comment by tfendt** [comment]
I also tried @felipesticksports suggestion and it did not work for me.

**Comment by tfendt** [comment]
I got it working by adding the following to the GoogleDependencyGooglePlayGames.xml file and then resolving client jars.

```xml
<dependency><groupId>com.google.android.gms</groupId><artifactId>play-services-auth</artifactId><version>9+</version></dependency>
```

**Comment by claywilkinson** [comment]
Auth is added back in  version 0.9.35 of the plugin (which depends on play-services 9+)
