### ISSUE TITLE
Facebook auth (using prime31) fails after updating gpgs plugin to 0.9.53

### ISSUE THREAD

**Issue by vaspotapov** [playgameservices/play-games-plugin-for-unity#2364]
Hi! Maybe someone can help here. I'm using prime31 for facebook authentication, and google-play-games-for-unity plugin for play games authentication. Recently I've updated gpgs plugin to 0.9.53 from 0.9.42, and when I try to login to fb I see this error:

11-19 14:48:54.330: E/Unity(27700): Exception in callback: System.TypeInitializationException: An exception was thrown by the type initializer for Prime31.FacebookAndroid ---> UnityEngine.AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/login/LoginBehavior;
11-19 14:48:54.330: E/Unity(27700): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/login/LoginBehavior;
11-19 14:48:54.330: E/Unity(27700): at com.prime31.FacebookPlugin.(FacebookPlugin.java:54)
11-19 14:48:54.330: E/Unity(27700): at com.prime31.FacebookPluginBase.instance(FacebookPluginBase.java:39)
11-19 14:48:54.330: E/Unity(27700): at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-19 14:48:54.330: E/Unity(27700): at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
11-19 14:48:54.330: E/Unity(27700): at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
11-19 14:48:54.330: E/Unity(27700): at android.os.MessageQueue.next(MessageQueue.java:479)
11-19 14:48:54.330: E/Unity(27700): at android.os.Looper.loop(Looper.java:144)
11-19 14:48:54.330: E/Unity(27700): at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
11-19 14:48:54.330: E/Unity(27700): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.login.LoginBehavior" on path: DexPathList[[zip file "/data/app/com.CarXTech.CarXDriftRacingFull-zypLfT5UShuOzqnayK 11-19 14:52:50.794: E/Unity(27700): AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/login/LoginBehavior;
11-19 14:52:50.794: E/Unity(27700): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/login/LoginBehavior;
11-19 14:52:50.794: E/Unity(27700): at com.prime31.FacebookPlugin.(FacebookPlugin.java:54)
11-19 14:52:50.794: E/Unity(27700): at com.prime31.FacebookPluginBase.instance(FacebookPluginBase.java:39)
11-19 14:52:50.794: E/Unity(27700): at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-19 14:52:50.794: E/Unity(27700): at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
11-19 14:52:50.794: E/Unity(27700): at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
11-19 14:52:50.794: E/Unity(27700): at android.os.MessageQueue.next(MessageQueue.java:479)
11-19 14:52:50.794: E/Unity(27700): at android.os.Looper.loop(Looper.java:144)
11-19 14:52:50.794: E/Unity(27700): at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
11-19 14:52:50.794: E/Unity(27700): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.login.LoginBehavior" on path: DexPathList[[zip file "/data/app/com.CarXTech.CarXDriftRacingFull-zypLfT5UShuOzqnayKzC6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.CarXTech.CarXDriftRacingFull-zypLfT5UShuOzqnayKzC6g==/lib/arm, /data/app/com.CarXTech.CarXDrif
11-19 14:52:52.945: E/Unity(27700): java.io.EOFException
11-19 14:52:52.945: E/Unity(27700):
11-19 14:52:52.945: E/Unity(27700): (Filename: Line: 390)

List of my jars in Plugin/Android folder:
android.arch.core.common-1.0.0
android.arch.lifecycle.common-1.0.0
android.arch.lifecycle.runtime-1.0.0
com.android.support.customtabs-26.1.0
com.android.support.support-annotations-26.1.0
com.android.support.support-compat-26.1.0
com.android.support.support-core-ui-26.1.0
com.android.support.support-core-utils-26.1.0
com.android.support.support-fragment-26.1.0
com.android.support.support-media-compat-26.1.0
com.android.support.support-v4-26.1.0
com.google.android.gms.play-services-ads-15.0.1|
com.google.android.gms.play-services-ads-base-15.0.1
com.google.android.gms.play-services-ads-identifier-15.0.1
com.google.android.gms.play-services-ads-lite-15.0.1
com.google.android.gms.play-services-auth-16.0.1
com.google.android.gms.play-services-auth-api-phone-16.0.0
com.google.android.gms.play-services-auth-base-16.0.0
com.google.android.gms.play-services-base-16.0.1
com.google.android.gms.play-services-basement-16.0.1
com.google.android.gms.play-services-drive-16.0.0
com.google.android.gms.play-services-games-16.0.0
com.google.android.gms.play-services-gass-15.0.1
com.google.android.gms.play-services-gcm-16.0.0
com.google.android.gms.play-services-iid-16.0.0
com.google.android.gms.play-services-nearby-16.0.0
com.google.android.gms.play-services-stats-16.0.1
com.google.android.gms.play-services-tasks-16.0.1
com.google.games.gpgs-plugin-support-0.9.53
FacebookPlugin
flurryAnalytics
FlurryPlugin
gameanalytics
ImmersiveMode
ParsePush
Prime31UnityActivity
ShortcutBadger-1.1.21
utnotifications

Also, I've noticed that with version 0.9.42 of gpgs I've had these jars,:
facebook-android-sdk-4.28.0
facebook-applinks-4.28.0
facebook-common-4.28.0
facebook-core-4.28.0
facebook-login-4.28.0
facebook-messenger-4.28.0
facebook-places-4.28.0
facebook-share-4.28.0

But with updating after resolving jars none of them occured.

**Comment by vaspotapov** [comment]
привет) yes, I've tried, but no result. I'm trying manually add these fb jars to Android folder now.

**Comment by vaspotapov** [comment]
So I've fixed issue. The problem was that my Plugins/Android/ folder was missing some of jars. So here is fix steps for anyone who might be encounted this issue in future:
For prime31 facebook proper integration you need to be sure you have these jars in your Plugins/Android folder:
(these you can get from facebook-unity-sdk, version might differ)
facebook-android-sdk-4.28.0
facebook-applinks-4.28.0
facebook-common-4.28.0
facebook-core-4.28.0
facebook-login-4.28.0
facebook-messenger-4.28.0
facebook-places-4.28.0
facebook-share-4.28.0
bolts-android-1.4.0
bolts-applinks-1.4.0
bolts-tasks-1.4.0
(these you can get from your local android sdk/extras/android/m2repository/com/android/support)
appcompat-v7-25.3.1
cardview-v7-25.3.1

After adding jars from list above everything should work like a charming charm.

**Comment by vaspotapov** [comment]
Sure. Checked - manually added files have not been deleted, only com.google.android.* and com.android.* jar metas was modified

**Comment by olehkuznetsov** [comment]
Thanks for the update, sounds as a good solution =)

**Comment by vaspotapov** [comment]
thanks=)
