### ISSUE TITLE
GooglePlayGamesPlugin-0.9.21 not working on Unity 4.6.6

### ISSUE THREAD

**Issue by vanustwo** [playgameservices/play-games-plugin-for-unity#605]
I'm importing new package in Unity 4.6.6

The following error is produce in GPGSPostBuild.cs

Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(24,23): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?

**Comment by CobaltD** [comment]
Try install google plus sdk http://goo.gl/9cTqyZ or use NO_GPGS define.

**Comment by Qbit86** [comment]
Yes, plugin is broken in Unity 4.6 since developers have only tested (if ever) building in Unity 5. They are using classes that are unavailable in Unity 4.6 and no compilation guards added.

**Comment by KyTn** [comment]
hi! just to try with v4.6.1 and v5.0.1b1, and they both dont work. Perhaps in v5.1.1f1 seems that it works!!

**Comment by KhinRunite** [comment]
So, do we file it as an issue with Unity, or is there any fix on the plug-in's part?

**Comment by KyTn** [comment]
I think that is part of a bug of this plugin, because not all versions of unity 5 has the same modules.

**Comment by claywilkinson** [comment]
Unity renamed the constant from iPhone to iOS somewhere along the way.  We'll update the plugin soon with the fix, #618 .  In the mean time, you can change the constant back.

**Comment by NitishKumar19** [comment]
I'm using Unity 4.6.7 and after updating the plugin from 0.9.15 to 0.9.21 getting the same error:
"Assets/GooglePlayGames/Editor/GPGSPostBuild.cs(24,23): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?"

Could you please advice which constant has to be changed back (and to what) in order to fix this error in GPGSPostBuild.cs?

Background: I have to update to the plugin in order to try and fix the Google Sign-in flow error we're seeing with il2cpp on Unity 4.6.7 and the 0.9.15 plugin. We're stuck uploading the app to Apple so a fix is critically needed. Thanks for the help.

**Comment by claywilkinson** [comment]
change iOS to iPhone on the line you are getting the error.

**Comment by fnicu** [comment]
Not working for me changing iOS to iPhone.
"The Type or namespace name 'iPhone' does not exist in the namespace 'UnityEditor'. Are you missing an assembly reference?"
Any help?

**Comment by SHAANBHAYA** [comment]
Nope,not working ..I don't think UnityEditor has ever had any namespace called as Iphone .

**Comment by claywilkinson** [comment]
Ohh - I see - yes, that is a new namespace for 5.0   Are you building for iOS currently?  If not, you can just remove the line and the contents of UpdateGeneratedPbxproj() as a temporary workaround.

I'll take a look and see what can be done for making it work with iOS and 4.6

**Comment by fnicu** [comment]
I'm working with Android, Actually i add GooglePlayGamesPlugin to fix a GooglePlayGames error, and then this error appears.

**Comment by claywilkinson** [comment]
Ok - I updated the plugin unitypackage to be compatible with 4.x Thanks for reporting this issue.

**Comment by jjjuande** [comment]
This error also happens in Unity 5.3.2 if you don't have the "Build for iOS" module installed.
