### ISSUE TITLE
Build Unity project in Xcode  ERROR in GTMOAuth2ViewControllerTouch.h

### ISSUE THREAD

**Issue by asadmehmoodlogicon** [playgameservices/play-games-plugin-for-unity#1460]
Hello, all.

I recently have problems related play-games-plugin in xCode.
It used to work in last week but it suddenly causes following problems and fails to complile.

Here are my project stauts.

xCode version 8
Unity version 5.3.4p5
Google play game unity for Unity version 0.9.31
Cocoapods applied for xCode project with following settings.

platform :ios, '7.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '~> 5.0'
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
end
end
end

1st, if I try to build, xCode complains with following message
...../XXX_iOS/Pods/GTMOAuth2/Source/Touch/GTMOAuth2ViewControllerTouch.m:331:41: Use of undeclared identifier 'GTMOAuth2ErrorTokenUnavailable'; did you mean 'kGTMOAuth2ErrorTokenUnavailable'?

I choose to auto fix in xCode which changes GTMOAuth2ErrorTokenUnavailable to kGTMOAuth2ErrorTokenUnavailable in GooglePlusOneSource.....

2nd, after I finish the auto fix for 1st, then I got following error at the end of compilation.
Undefined symbols for architecture arm64:
"OBJC_CLASS$GSDK_GTMSessionFetcher", referenced from:
objc-class-ref in gpg(GPGClearcutLogger.o)
"_OBJC_CLASS$_GSDK_GTMSessionFetcherService", referenced from:
objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

To fix this, I tried many other ways such as add GoogleOpenSource.framework, add Google sign in, and etc, but no lucks so far.

Any other ideas will be very helpful!!

**Comment by Ugobyte** [comment]
Same here. 

Also, I just updated my GooglePlayServices. Now when i do a Unity build for iOS. Unity builds a folder with an XCode project. It used to build an XCode workspace.
Am I missing something?

**Comment by MishaPh** [comment]
Hello

i have this problem too. But after updated GooglePlayServices to v0.9.35, error with "GTMOAuth2ErrorTokenUnavailable" be fixed.

But I got following error
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in GoogleSignIn(GIDRuntimeConfigFetcher.o)
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)

I'm download and install the sample project "CubicPilot", using step-by-step.
(When I got compilation error "undefined symbols" too)

xCode version 7.3.1
Build "ios" target  = 7.0
Unity version 5.3.3p1
Google play game unity 0.9.35

**Comment by leandro-zanardi** [comment]
same here
xcode 8
play services 0.9.35
ios target 8
pod 1.1.1

Using GTMOAuth2 (1.1.4)
Using GTMSessionFetcher (1.1.7)
Using GoogleAppUtilities (1.1.2)
Using GooglePlayGames (5.1.1)
Using GooglePlusOpenSource (1.7.1)
Using GoogleSignIn (4.0.1)
Using GoogleSymbolUtilities (1.1.2)
Using GoogleToolboxForMac (2.1.0)



Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in GoogleSignIn(GIDRuntimeConfigFetcher.o)
      objc-class-ref in GoogleSignIn(GIDSignIn.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcher", referenced from:
      objc-class-ref in gpg(GPGClearcutLogger.o)
  "_OBJC_CLASS_$_GSDK_GTMSessionFetcherService", referenced from:
      objc-class-ref in gpg(GIPNetworkImage.o)
ld: symbol(s) not found for architecture arm64

**Comment by gnchishti** [comment]
any reply from google play service developers?

**Comment by asadmehmoodlogicon** [comment]
Finally I Solved this issue by changing the pod file to this
platform :ios, ‘8.0’

target 'Unity-iPhone' do
pod 'GooglePlayGames', ‘5.1’
pod 'Google'
end
target 'Unity-iPhone Tests' do
pod 'GooglePlayGames', ‘5.1	’
pod 'Google'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
then install the pod file and its done no error

**Comment by Ugobyte** [comment]
@asadmehmoodlogicon Does your Unity build an Xcode workspace? When i do a build, it's only building an Xcode project.

**Comment by kukoss** [comment]
I tried same steps, but I still ended up with few errors :( I am a bit sad I cannot implement google play services in my iOS games. Could have been great. :(

![screen shot 2016-10-31 at 02 14 54](https://cloud.githubusercontent.com/assets/23157947/19841814/79a14cbe-9f11-11e6-97dd-44a0ffc9d11a.png)

**Comment by asadmehmoodlogicon** [comment]
@Ugobyte  Yes for workspace you should install the pod then the workspace file will apear

**Comment by asadmehmoodlogicon** [comment]
@kukoss its the only solution working around over the internet for now
please check the pod file its the only issue

**Comment by kukoss** [comment]
Hi @asadmehmoodlogicon , please, could you just check my screenshots if everything looks ok to you? 

1 - I set my unity build like this
![screen shot 2016-10-31 at 12 14 29](https://cloud.githubusercontent.com/assets/23157947/19852507/063780e2-9f64-11e6-9fbf-f9f365a39a1a.png)

2 - Then I open cocoapods 1.0.0 and run the pod file above and install

![screen shot 2016-10-31 at 12 19 05](https://cloud.githubusercontent.com/assets/23157947/19852550/4d4713f8-9f64-11e6-9ec7-f2c90c8a5fd4.png)

![screen shot 2016-10-31 at 12 20 16](https://cloud.githubusercontent.com/assets/23157947/19852565/68dfed06-9f64-11e6-9d63-3a1971354e0f.png)

3 - I open xcworkspace file, in iphone project set provisioning account

![screen shot 2016-10-31 at 12 22 56](https://cloud.githubusercontent.com/assets/23157947/19852647/cf330336-9f64-11e6-8e09-b27a265cedb8.png)
 and hit cmd+B to build it



4 - I get the error above while linking

Please, do you think I am missing anything??

**Comment by leandro-zanardi** [comment]
this solution does not works for me.


Showing All Messages
  "_OBJC_CLASS_$_GTMSessionFetcherService", referenced from:
      objc-class-ref in GoogleSignIn(GIDSignIn.o)

  "_OBJC_CLASS_$_GTMSessionFetcher", referenced from:
      objc-class-ref in GoogleSignIn(GIDRuntimeConfigFetcher.o)
      objc-class-ref in GoogleSignIn(GIDSignIn.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by leandro-zanardi** [comment]
1 week to try build the project without success. My unique solution is remove play services from my projects. I cannot release new versions in production products and create new projects.

**Comment by MishaPh** [comment]
Ok
After update xcode to v8.1, and Unity to 5.4.0p1. Build "test-project"  be success. 
Now i try migrate main project to the new Unity version.

**Comment by kukoss** [comment]
@MishaPh let us know if updating unity helps to build it with google play services

**Comment by leandro-zanardi** [comment]
in my last breath, made it work.
my steps:
1 - complete remove cocoapods from system 
gem list --local | grep cocoapods
and so 
gem uninstall cocoapods ... one by one of listed

2 - install cocoapods again
sudo gem install cocoapods

3- remove all pods from project, folder and Podfile.lock

4 - use this Podfile
platform :ios, '8.0'

target 'Unity-iPhone' do
pod 'GooglePlayGames', '5.1'
end

5 - pod install

6 - remove google sigin from build phases library ( either this framework is not present in pods anymore, but it it still logging and working )

7 - in Capabiliites from project in xcode enable Associated Domains and Game Center

tested project with multiplayer realtime connection between android and ios.

xcode 8
unity 5.4.1f1

**Comment by Blinkq** [comment]
@leandro-zanardi Thanks, its works for me. I think step 6 is the key.

**Comment by kukoss** [comment]
@leandro-zanardi , @Blinkq guys, could you please explain what does step 6 mean? How to remove it? the whole google sign in framework? or what exactly? 

thank you :)

**Comment by Blinkq** [comment]
@kukoss In xCode in Build Phases in Libraries find and remove GoogleSign.framework

**Comment by kukoss** [comment]
thank you all. step number 6 is crucial. i did not change anything else except I only removed the google sign in lib in Build Phases

**Comment by kukoss** [comment]
Hi guys,

after i removed google sign in framework from the linked libs, I compiled everything and tested it out. Sign in, scores, leaderboards, everything work. However, when I created IPA to be published in the app store, I received this error when trying to submit the app.

![screen shot 2016-11-01 at 22 55 49](https://cloud.githubusercontent.com/assets/23157947/19910575/3a217e32-a08e-11e6-880f-507225b51704.png)

What I had to do was to go to the xcode project folder, search GoogleSignIn.bundle and delete the file through Finder. Then I cleaned the app again, compiled and everything worked + I was able to submit IPA to the app store.

good luck :)

**Comment by gnchishti** [comment]
Hi, @kukoss 

While submitting I had the same error, then I removed GoogleSignIn.bundle from project. But in that case my XCode give error of its non availability.

Could you share your pod file?

**Comment by kukoss** [comment]
Hi @gnchishti , I had to find it as a file somewhere in the project and delete it from the disk. Then I cleaned the solution and it worked.

Second time, I was building new version of my app, my solution for some reason did not work :) So I found all references to googlesignin bundle and commented them out and suddenly it worked. I do not know the exact file name because I don't have my Mac, but that was the key. Basically there were two references for this library in ONE file somewhere in bundles folder in Xcode

**Comment by gnchishti** [comment]
I just deleted info.plist in GoogleSignIn.bundle, it worked for me.

:) I just uploaded my build

**Comment by kukoss** [comment]
That's it. Plist:):) congratulations:)

**Comment by asotelo94** [comment]
So I finally got it to work by removing the GoogleSignIn references. However know I am getting this:

![img_2065](https://cloud.githubusercontent.com/assets/6198320/20940905/60087840-bbc2-11e6-80cb-019ce14414b3.PNG)

It seems that I have to have the SignIn stuff or am I wrong?

**Comment by santiandrade** [comment]
I have the "disallowed_useragent" error too when my IOS game try to login in Google :-(
Please, anyone knows what's the solution for that??

**Comment by andrewio** [comment]
@santiandrade same problem =(

**Comment by claywilkinson** [comment]
Unfortunately, GPGS has been deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html
