### ISSUE TITLE
GoogleCloudMessaging class not found, push notifications stop working.

### ISSUE THREAD

**Issue by doterax** [playgameservices/play-games-plugin-for-unity#883]
After update to v00927 plugin, our game start rarelly crush in backround. Google Play developer console show crush stack in GoogleCloudMessaging handler:

**Crush stack**:
```
java.lang.NoClassDefFoundError: com.google.android.gms.gcm.GoogleCloudMessaging
at com.candygrill.gcm.GcmIntentService.onHandleIntent(GcmIntentService.java:26)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:175)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

**GcmIntentService.java** (relevant part of file)
```
protected void onHandleIntent(Intent intent) 
{
    Bundle extras = intent.getExtras();  
    GoogleCloudMessaging gcm = GoogleCloudMessaging.getInstance(this); // Line 26
	...
}
```

I explore all *.AAR files in Plugins\Android and in classes.jar I do not find package com.google.android.gms.gcm 

I think you forgot include this package to AAR files.

**Comment by claywilkinson** [comment]
Google Play Games Services does not use GCM.  This is coming from another part of code.  You can include the .aar file you need which is in $ANDROID_HOME/extras/google/m2repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.aar

(or select the version that matches the other play-services aar files, e.g. 8.1.0)

**Comment by doterax** [comment]
Thank you for explanation.
