### ISSUE TITLE
Leaderboard Scores fail to update after first fetch / load.

### ISSUE THREAD

**Issue by Tehelee** [playgameservices/play-games-plugin-for-unity#1534]
Steps to reproduce:

1. Use Social.ReportScore() to upload a score
2. Use any method to fetch / load scores, such as PlayGamesPlatform.Instance.LoadScores()
3. Use Social.ReportScore() to upload a larger (better) score (or smaller depending on your leaderboard setting)
4. Use any method to fetch / load scores, such as PlayGamesPlatform.Instance.LoadScores()

The score will not change, however if you use Social.ShowLeaderboardUI() the score listed will be updated.

Notes: 
The IScore 'PlayerScore' returned in the LeaderboardScoreData object from PlayGamesPlatform.Instance.LoadScores() will have the updated value, contrary to the value(s) reported in the IScore array 'Scores' of that same LeaderboardScoreData object.

The values loaded from LeaderboardCollection.Public and LeaderboardCollection.Social are seperate and both will load once initially. If you first use Public, then update the score, Public will still show the old value,. However Social will do its first fetch and find the updated score, then never update again.

I have tried every combination I can think of to troubleshoot and / or work around; I have narrowed the issue down to this plugin as demonstrated by the updated score in Social.ShowLeaderboardUI().
Somehow the value is being cached even through data / cache wipes and reinstalls.

@hak - I think this is a serious issue that should be resolved asap, thanks for all the work you've done so far.

**Comment by claywilkinson** [comment]
Thanks for the detailed debugging steps.  I'll pass along the information.  At a high level, is it accurate to say that the loadScores does not return updated scores until ShowLeaderboardUI is called?  (And your "Notes" section is identifying the various caches.)

**Comment by Tehelee** [comment]
LoadScores will fail to return updated scores at all, even after calling ShowLeaderboardUI.

**After more debugging, it appears this is a PlayerCentered issue.**
LoadScores will fetch updated scores if LeaderboardStart is TopScores rather than PlayerCentered.

**Comment by claywilkinson** [comment]
Thanks for the clarification!  I'll pass it along.

**Comment by Tehelee** [comment]
Using any configuration of the ILeaderboard object created from PlayGamesPlatform.Instance.CreateLeaderboard() also results in incorrect scores.
As usual the localUserScore is updated, but the user's score in the IScore array contains the wrong value.

**Comment by claywilkinson** [comment]
I am looking into this today.  Once thing that you might want to hack to see if makes a difference is to change [LeaderboardManager.LoadLeaderboardData()](https://github.com/playgameservices/play-games-plugin-for-unity/blob/master/source/PluginDev/Assets/GooglePlayGames/Platforms/Native/PInvoke/LeaderboardManager.cs#L109) to use Types.DataSource.NETWORK_ONLY vs. CACHE_OR_NETWORK.  Also, to look at the result code returned to see if it is VALID or VALID_STALE.

I'll update the thread after  I try this as well.

**Comment by claywilkinson** [comment]
I was able to reproduce the issue and passed along the information to the engineering team.  I'll update the thread when I know more.  Thanks again for your debugging!

**Comment by DutchGuerrillia** [comment]
Yep, 'just want to let you know I'm facing the same problems :( Please fix this issue. I guess this has something to do with new leaderboards. Because lots of developers used the Play services in their games..

Cheers,
Maarten

**Comment by DutchGuerrillia** [comment]
Hello Tehelee,

I solved the problem for me. I did a few things, but the thing I suspect that did the trick is changing the following parameter:

PlayGamesPlatform.Instance.LoadScores(
        gPGSIds,
        LeaderboardStart.**TopScores**,
        recordsTotal,
        LeaderboardCollection.Public,
        leaderboardTimeSpan,
        (data) => {}

You see after LeaderboardStart I changed to TopScores instead of PlayerCentered.

Now I can ad new scores.

I also changed the following, but I thing it has nothing to do with the solution:

- Changed Unity game version
- Put the Game play Services to production
- Add a test button to request the google scoreboards interface. Opent that once, but add my wives Phone I didn't even thoughed that button...so...no..

Hope it helps,

Cheers,
Maarten

**Comment by zory** [comment]
First I thought it was UserCentered bug as well, but after more debug'ing I came up with another theory.

It seems, that then one user sends score (but dont get scores himself) other player will not see this score. I tried playing with Types.DataSource.NETWORK_ONLY parameters, but there were always at least one case then score wouldn't update. If user who have sent score downloaded scores for himself (not sure if Types.DataSource matters, tried a lot variants), then other user will get good scores too.

My workaround:
Right after posting score, try to download my score forceing to download it with NETWORK_ONLY.
`
Social.ReportScore(score, leaderboardID, (bool success) => {
   if (success)
   {
      FetchFix(leaderboardID, 0);
   }
});
`
And
`
private static void FetchFix(string leaderboardID, int tryCounter)
{
   PlayGamesPlatform.Instance.LoadScores(leaderboardID, LeaderboardStart.PlayerCentered, 1, LeaderboardCollection.Public, LeaderboardTimeSpan.AllTime, DataSourceType.NETWORK_ONLY, (LeaderboardScoreData data) => {
      if (data != null && (data.Status == ResponseStatus.InternalError || data.Status == ResponseStatus.Timeout) && tryCounter <= 5)
      {
         FetchFix(leaderboardID, ++tryCounter);
      }
   });
}
`
It seems, this workaround work for me. If you will see some situation there it might be wrong, comment.
Sorry, something happened with code formatting.

**Comment by Mukikaizoku** [comment]
@zory Thanks for the workaround, I'm trying to add it, but I'm a bit confused. I found the enum parameter DataSource.ReadNetworkOnly, but I don't see any overload for PlayGamesPlatform.Instance.LoadScores that takes it as a parameter. Could you perhaps give some more details?

**Comment by zory** [comment]
Sorry for late reply.
Yes, there is no overloaded method, I added method with one more additional argument.
So basically you can use code I pasted before just add following things:

1)
PlayGamesPlatform.cs
Add argument to LoadScores method **DataSourceType dataSourceType**, then pass it `mClient.LoadScores(leaderboardId, start, rowCount, collection, timeSpan, dataSourceType, callback);`

2)
Also add or change IPlayGamesClient.cs LoadScores method accordingly and implement it in DummyClient and NativeClient:
`public void LoadScores(string leaderboardId, LeaderboardStart start, int rowCount, LeaderboardCollection collection, LeaderboardTimeSpan timeSpan, DataSourceType dataSourceType, Action<LeaderboardScoreData> callback)`
and pass it to to leaderboardManager in
`LoadLeaderboardData(.blah blah blah, dataSourceType, blah blah)`

3)
change Types.DataSource.NETWORK_ONLY to your value in LoadLeaderboardData (LeaderboardManager).

After every score posting we downloading one score, but i guess it is better than having out of sync leaderboards.
Hope it helps

**Comment by asadrana91** [comment]
i am having the same issue, leaderboard only updates the first time for a user , anyone found the solution? secondly i needed to ask, my game is still in testing phase, do we need to publish the game before? or it should work fine in testing phase?

**Comment by zory** [comment]
It should work without publishing (after publishing certain things can't be changed!).
You can try solution mentioned before. If it works, let us know.

**Comment by Mukikaizoku** [comment]
@zory Thanks for the additional details! My reply was late as well, just finally getting back to this issue..

Anyway, I implemented your workaround and I got it to work! I needed to do go a step further and modify LeaderboardManager.HandleFetch (), which is the callback passed to C.LeaderboardManager_Fetch () called in LeaderboardManager.LoadLeaderboardData (). Within HandleFetch (), I changed Types.DataSource.CACHE_OR_NETWORK to Types.DataSource.NETWORK_ONLY within C.LeaderboardManager_FetchScoreSummary().

@claywilkinson Along the lines with this workaround, should we be managing the DataSource type to limit the number of calls for fresh data?

**Comment by Firemaw** [comment]
I can confirm having the same issue as original poster. Setting LeaderboardManager.LoadLeaderboardData() to use Types.DataSource.NETWORK_ONLY did not fix the issue for me.

**Comment by jeffries7** [comment]
Is anyone else still having this issue? I'm using Unity 5.6.2p1 along with Play Games 0.9.37 and leaderboard scores only return when the LeaderboardStart is set to TopScores.

If I set it to PlayerCentered it just returns 1 for every player.

**Comment by Firemaw** [comment]
I am using Unity 5.6.2f1 with GPGS 0.9.36 and the following code returns 5 players centered around the logged in user correctly:

```
string leaderboardID = "l123456";
PlayGamesPlatform.Instance.LoadScores (leaderboardID, LeaderboardStart.PlayerCentered, 5, LeaderboardCollection.Public, LeaderboardTimeSpan.AllTime, (LeaderboardScoreData lsd) =>
{
  if (lsd.Valid)
  {
    // Do work with lsd
  }
  else
  {
    Debug.Log ("Invalid or no data for competitors was returned - user may not have submitted a score yet");
  }
);
```

**Comment by jeffries7** [comment]
Have you made any changes to Play Games Platform as i've take your example and I still get the same results. The only other thing is that my leaderboard status is "Ready to publish", but that shouldn't make a difference.

**Comment by Firemaw** [comment]
Yes I had to change some references to Types.DataSource.NETWORK_ONLY as in another post above, otherwise it would keep returning the old cached data.

**Comment by BlueSpiritbox** [comment]
I'm having this issue as well with 0.9.50. It's not returning any scores if I called LoadScores() after I report a score. It works fine if I call it before reporting a score. I tried the suggested workarounds by changing Types.DataSource.CACHE_OR_NETWORK to Types.DataSource.NETWORK_ONLY and LeaderboardStart.PlayerCentered to TopScores, but no luck.

**Comment by Mokalipilou** [comment]
Hi,
do we have any way to fix this 15 month old problem without altering GPG plugin files, being exposed to problems on future plugin updates?

On side note, having a broken caching system will only encourage temporary fixes that will ultimately lead to more problems. Is a proper fix planned at any point?

**Comment by jeffries7** [comment]
As far as i'm aware this is still an issue

**Comment by JDeuce** [comment]
I can also confirm this issue is impacting me on Unity 2017.4.1f1 with 0.9.50.

I am using leaderboard = Social.CreateLeaderboard() followed by leaderboard.LoadScores().

After submitting my first score, the leaderboard was able to fetch the data.

With subsequent updates to the score, it still successfully returns from the load but only my original score is returned. If I open the default android UI with Social.ShowLeaderboardUI() then I can see the score has been correctly updated with Android Game Services.

Exiting the application and restarting it makes no difference, it still continues to use the cache.

**Comment by itsdrew** [comment]
Confirmed as well. I am on 2017.3.1f1 with 0.9.50.
Attempting to fix.
In LeaderboardManager.cs, in the HandleFetch method i've changed Types.DataSource.CACHE_OR_NETWORK to Types.DataSource.NETWORK_ONLY.

`            C.LeaderboardManager_FetchScoreSummary(mServices.AsHandle(),
				**Types.DataSource.NETWORK_ONLY,**
                token.LeaderboardId,
                (Types.LeaderboardTimeSpan)token.TimeSpan,
                (Types.LeaderboardCollection)token.Collection,
                InternalFetchSummaryCallback,
                Callbacks.ToIntPtr<FetchScoreSummaryResponse>((rsp) =>
                    HandleFetchScoreSummary(data, rsp, selfPlayerId, maxResults, token, callback),
                FetchScoreSummaryResponse.FromPointer)
            );`

Hopefully that will work, will post back later after testing.

**Comment by Majter** [comment]
Hello guys, I have this kind of problem and start to print some values to figure out what is going on.
NOTE: (I did this without changing Types.DataSource)

PlayGamesPlatform.Instance.LoadScores(
            GPGSIds.leaderboard_leaders_in_smoketesting,
            LeaderboardStart.PlayerCentered,
            100,
            LeaderboardCollection.Public,
            LeaderboardTimeSpan.AllTime,
            (data) =>
            {
                Debug.Log( "Valid: " + data.Valid + "Status: " + data.Status + " playerScore: "+ data.PlayerScore.value + " : " + data.PlayerScore.formattedValue );
            });

The player score stored in data.PlayerScore.value (callback of PlayGamesPlatform.Instance.LoadScores) was different than the one stored in data.Scores[indexOfCurrentPlayer].value

For me, the updated one was the stored in data.PlayerScore.value 
The value stored in data.Scores[indexOfCurrentPlayer].value was out of date (at least for the current user).

To me, the more important thing is to show the correct value to the current user. I hope this work for you.

**Comment by mgrogin** [comment]
Thanks for the quick response @itsdrew ! 
I see in GooglePlayGames.Native.Cwrapper.GameServices theres a function called GameServices_Flush.
I'm just not sure how to use it :)

**Comment by YiorgosX** [comment]
I'm having the same issue, with a twist: some of my beta testers can constantly upload scores, some other cannot, at all. All using the same build, of course. Anyone has experienced this?

**Comment by ignacevau** [comment]
I can confirm that this has issue has not been fixed yet. I'm using Unity 2018.2.11f1 with the plugin version 0.9.53. Using 'TopScores' returned the updated values, 'PlayerCentered' did not. Using the workaround of @itsdrew  did the trick for me.

**Comment by AMastryukov** [comment]
This issue persists for me as well. I verify that my scores are successfully reported and then check the leaderboard by calling PlayGamesPlatform.Instance.LoadScores() with TopScores and then PlayGamesPlatform.Instance.ShowLeaderboardUI() if the data returned from LoadScores() is valid. The scores update sometimes but most times they do not. I have used @itsdrew's solution by changing the plugin to use NETWORK_ONLY.

I'm starting to think that PlayGamesPlatform.Instance.ShowLeaderboardUI() is not very well-made and a custom leaderboard screen might be required for this.

**Comment by CatalystJesal** [comment]
I can also confirm that I'm having trouble getting the leaderboard to update correctly. There has been cases where stale scores have been shown (via cache) and further additional records of new player scores not showing up. When I look into my app on the Google Play Console and navigate to the Leaderboard, it shows I have 7 unique entries, however the app only shows 5 and updates those scores, sometimes certain scores will update and other times they won't....I use the `PlayGamesPlatform.Instance.ShowLeaderboardUI()` to show the leaderboard.  This has also been an issue during testing.

Google Play Services plugin version: 0.9.64

**Comment by kcheeb** [comment]
unbelievable google still didnt address this issue

**Comment by kcheeb** [comment]
> Sorry for late reply.
> Yes, there is no overloaded method, I added method with one more additional argument.
> So basically you can use code I pasted before just add following things:
> 
> 
> PlayGamesPlatform.cs
> Add argument to LoadScores method **DataSourceType dataSourceType**, then pass it `mClient.LoadScores(leaderboardId, start, rowCount, collection, timeSpan, dataSourceType, callback);`
> 
> 
> Also add or change IPlayGamesClient.cs LoadScores method accordingly and implement it in DummyClient and NativeClient:
> `public void LoadScores(string leaderboardId, LeaderboardStart start, int rowCount, LeaderboardCollection collection, LeaderboardTimeSpan timeSpan, DataSourceType dataSourceType, Action<LeaderboardScoreData> callback)`
> and pass it to to leaderboardManager in
> `LoadLeaderboardData(.blah blah blah, dataSourceType, blah blah)`
> 
> 
> change Types.DataSource.NETWORK_ONLY to your value in LoadLeaderboardData (LeaderboardManager).
> 
> After every score posting we downloading one score, but i guess it is better than having out of sync leaderboards.
> Hope it helps

Assets\GooglePlayGames\Platforms\Native\PInvoke\LeaderboardManager.cs(93,4): error CS0246: The type or namespace name 'DataSourceType' could not be found (are you missing a using directive or an assembly reference?)

**Comment by kcheeb** [comment]
> I'm having the same issue, with a twist: some of my beta testers can constantly upload scores, some other cannot, at all. All using the same build, of course. Anyone has experienced this?

I am testing on 3 devices. 2 of my devices can upload scores, while 1 cannot. This is extremely retarded

**Comment by NeuralEvolution** [comment]
I am having this exact same issue. It only happens as stated above with PlayerCentered scores. Why has this not been fixed it was opened in 2016. Is anyone from google even looking into this?

**Comment by dipaninside** [comment]
Still the Plugin showing outdated data. Cant fix it to load from network. somebody help please.

**Comment by luizhm0reira** [comment]
Is this issue solved? Any update please?
thank you

**Comment by Mhmdpnk** [comment]
Still having same issue and LeaderboardManager.cs does not exist in latest plugin to fix the load from network. Any updates?

**Comment by mura94** [comment]
Any updates on this? Running into the same problem.

**Comment by CoreyHendrey** [comment]
Just chiming in to say I'm running into the same problem.

**Comment by RafalWilkowski** [comment]
I'm working on GooglePlayGamesPlugin - 0.10.11 and ran into the same problem. I tried to get all-time rank and daily rank on the start screen of my game. All-time rank fetched well, but daily fetched good once and then read from cache old value. So to solve it you need as mention above use NETWORK only. To do that you need to find AndroidClient.cs and method LoadScores(). Inside you find task: 
<pan><code>using (var task = client.Call\<AndroidJavaObject\>(loadScoresMethod 
 ,leaderboardId, AndroidJavaConverter.ToLeaderboardVariantTimeSpan(timeSpan), AndroidJavaConverter.ToLeaderboardVariantCollection(collection), rowCount))
</code></pan>
After rowCount you need to add additional bool argument which FORCE to use NETWORK only so it should look like this:
<pan><code>using (var task = client.Call\<AndroidJavaObject\>(loadScoresMethod 
 ,leaderboardId, AndroidJavaConverter.ToLeaderboardVariantTimeSpan(timeSpan), AndroidJavaConverter.ToLeaderboardVariantCollection(collection), rowCount, true))
</code></pan>
Be aware, as mentioned in Google Documentation:
FORCE REALOAD - If true, this call will clear any locally cached data and attempt to fetch the latest data from the server. This would commonly be used for something like a user-initiated refresh. Normally, this should be set to false to gain advantages of data caching.
Also in best practices:
Use the client libraries. The mobile client libraries employ a number of strategies to reduce the calls you make to the service. For instance, data for achievements and leaderboards is cached, so players can view their achievements as often as they like without requiring the service to make multiple calls.

But I don't have a choice, it need to be reloaded every time :)

**Comment by LASpencer** [comment]
I'm seeing the same issue with v0.11.01
I've tried using the workaround above, editing the client to force it to reload from the network, but it doesn't work.

Viewing the leaderboards through the Google Play app shows the up to date score on both public and social leaderboards, but even if you delete the cache, getting the public leaderboard through the API doesn't return your score.

**Comment by rpinto-centi** [comment]
any update, i have the same issue

**Comment by 256p** [comment]
> I've tried using the workaround above, editing the client to force it to reload from the network, but it doesn't work.

Actually, it helped me. In v0.11.01 in AndroidClient.cs I have added `true` argument for forceReload in LoadScores function on line 794. It looks like the problem is not in the unity plugin but in the android game services library.

**Comment by thomasroyer34** [comment]
[RafalWilkowski] is a lifesaver ! Thank you man...

**Comment by danangsugiartogt** [comment]
Up, still happened. Thanks [RafalWilkowski].
